/*
###############################################################
#  Generated by:      Cadence Innovus 15.23-s045_1
#  OS:                Linux x86_64(Host ID ieng6-ece-12.ucsd.edu)
#  Generated on:      Sun Feb 16 19:53:55 2025
#  Design:            add
#  Command:           saveNetlist add.pnr.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : Q-2019.12-SP5-3
// Date      : Thu Feb  3 13:32:20 2022
/////////////////////////////////////////////////////////////
module add (
	clk, 
	out, 
	x, 
	y, 
	z);
   input clk;
   output [5:0] out;
   input [3:0] x;
   input [3:0] y;
   input [3:0] z;

   // Internal wires
   wire intadd_0_A_2_;
   wire intadd_0_A_1_;
   wire intadd_0_B_2_;
   wire intadd_0_B_1_;
   wire intadd_0_SUM_0_;
   wire intadd_0_n3;
   wire intadd_0_n2;
   wire intadd_0_n1;
   wire n11;
   wire n12;
   wire [3:0] x_q;
   wire [3:0] y_q;
   wire [3:0] z_q;
   wire [5:0] out_wire;

   DFQD1 z_q_reg_3_ (.CP(clk),
	.D(z[3]),
	.Q(z_q[3]));
   DFQD1 z_q_reg_2_ (.CP(clk),
	.D(z[2]),
	.Q(z_q[2]));
   DFQD1 z_q_reg_1_ (.CP(clk),
	.D(z[1]),
	.Q(z_q[1]));
   DFQD1 z_q_reg_0_ (.CP(clk),
	.D(z[0]),
	.Q(z_q[0]));
   DFQD1 x_q_reg_3_ (.CP(clk),
	.D(x[3]),
	.Q(x_q[3]));
   DFQD1 x_q_reg_2_ (.CP(clk),
	.D(x[2]),
	.Q(x_q[2]));
   DFQD1 x_q_reg_1_ (.CP(clk),
	.D(x[1]),
	.Q(x_q[1]));
   DFQD1 x_q_reg_0_ (.CP(clk),
	.D(x[0]),
	.Q(x_q[0]));
   DFQD1 y_q_reg_3_ (.CP(clk),
	.D(y[3]),
	.Q(y_q[3]));
   DFQD1 y_q_reg_2_ (.CP(clk),
	.D(y[2]),
	.Q(y_q[2]));
   DFQD1 y_q_reg_1_ (.CP(clk),
	.D(y[1]),
	.Q(y_q[1]));
   DFQD1 y_q_reg_0_ (.CP(clk),
	.D(y[0]),
	.Q(y_q[0]));
   DFQD1 out_reg_0_ (.CP(clk),
	.D(out_wire[0]),
	.Q(out[0]));
   DFQD1 out_reg_2_ (.CP(clk),
	.D(out_wire[2]),
	.Q(out[2]));
   DFQD1 out_reg_3_ (.CP(clk),
	.D(out_wire[3]),
	.Q(out[3]));
   DFQD1 out_reg_5_ (.CP(clk),
	.D(out_wire[5]),
	.Q(out[5]));
   DFQD1 out_reg_4_ (.CP(clk),
	.D(out_wire[4]),
	.Q(out[4]));
   DFQD1 out_reg_1_ (.CP(clk),
	.D(out_wire[1]),
	.Q(out[1]));
   FA1D0 intadd_0_U4 (.A(x_q[1]),
	.B(y_q[1]),
	.CI(z_q[1]),
	.CO(intadd_0_n3),
	.S(intadd_0_SUM_0_));
   FA1D0 intadd_0_U3 (.A(intadd_0_A_1_),
	.B(intadd_0_B_1_),
	.CI(intadd_0_n3),
	.CO(intadd_0_n2),
	.S(out_wire[2]));
   FA1D0 intadd_0_U2 (.A(intadd_0_A_2_),
	.B(intadd_0_B_2_),
	.CI(intadd_0_n2),
	.CO(intadd_0_n1),
	.S(out_wire[3]));
   IAO21D0 U13 (.A1(intadd_0_n1),
	.A2(n12),
	.B(out_wire[5]),
	.ZN(out_wire[4]));
   CKAN2D0 U14 (.A1(intadd_0_n1),
	.A2(n12),
	.Z(out_wire[5]));
   CKAN2D0 U15 (.A1(n11),
	.A2(intadd_0_SUM_0_),
	.Z(intadd_0_A_1_));
   IAO21D0 U16 (.A1(n11),
	.A2(intadd_0_SUM_0_),
	.B(intadd_0_A_1_),
	.ZN(out_wire[1]));
   FA1D0 U17 (.A(x_q[0]),
	.B(y_q[0]),
	.CI(z_q[0]),
	.CO(n11),
	.S(out_wire[0]));
   FA1D0 U18 (.A(x_q[2]),
	.B(z_q[2]),
	.CI(y_q[2]),
	.CO(intadd_0_B_2_),
	.S(intadd_0_B_1_));
   FA1D0 U19 (.A(z_q[3]),
	.B(y_q[3]),
	.CI(x_q[3]),
	.CO(n12),
	.S(intadd_0_A_2_));
endmodule

